[package]
name = "storm-lua-build"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
description = "Lua project linking, source maps and coarse compiler API"

[lints]
workspace = true

[dependencies]
storm-lua-spec = { workspace = true }
storm-lua-syntax = { workspace = true }
storm-lua-analysis = { workspace = true }
storm-lua-minify = { workspace = true }
serde = { workspace = true }
sourcemap = "9.3"

serde_json = { workspace = true }
sha2 = "0.10"
