/** SDK操作の実行例。仮のゲーム世界ではなく、明示的な入力とテストホストです。 */
import type {PlaygroundProject} from './project.js';
export interface Recipe extends PlaygroundProject {id:string;group:string;description:string;features:string[]}
const source={$source:true},environment={$environment:true};
const ref=(path:string)=>({$ref:path});
const commands=[
 {kind:'color',rgba:[8,20,30,255]},{kind:'clear'},
 {kind:'color',rgba:[100,230,200,255]},
 {kind:'rect',x:2,y:2,width:14,height:8,fill:true},
 {kind:'line',from:[0,31],to:[63,31]},
 {kind:'circle',x:30,y:8,radius:6,fill:false},
 {kind:'triangle',points:[[43,2],[58,12],[41,12]],fill:true},
 {kind:'text',x:2,y:17,text:'SDK'},
 {kind:'textBox',x:22,y:16,width:40,height:12,horizontalAlign:0,verticalAlign:0,text:'RGBA'},
];
const bindings={values:{'host.offset':11,pcall:null},functions:{'math.abs':{returns:[99]},'host.echo':{operation:'echo'}}};
const base={kind:'storm-lua-playground',version:1} as const;
const mappedSource='local function twice(value)\n return value*2\nend\nfunction onTick()\n local unused=99\n output.setNumber(1,twice(input.getNumber(1))+2*3)\n debug.log("mapped",input.getNumber(1))\nend';
const debugSource='function onTick()\n local values={}\n output.setNumber(1,input.getNumber(1))\n debug.log("before error")\n output.setNumber(2,values.missing+1)\nend';
const mappedArtifact=(name:string)=>({kind:'storm-lua-artifact',version:1,code:ref(name+'.code'),map:ref(name+'.map')});
export const RECIPES:Recipe[]=[
 {...base,id:'source-map',group:'解析と変換',title:'Source Map / 最適化を説明する',environment:'game',
  description:'生成Luaと元snapshotを並べ、名前・式・インライン文脈・最適化理由・削除記録を確認します。この操作列ではLuaを実行しません。',
  features:['sourceMap','x_storm','validateSourceMap','reasons','inlineContexts','dispositions'],source:mappedSource,
  steps:[{op:'minify',source,options:{environment,sourceMap:true,sourceName:'controller.lua',zeroCostNewlines:false},as:'mapped'},{op:'inspectMap',artifact:mappedArtifact('mapped'),side:'generated',start:0}]},
 {...base,id:'source-map-modules',group:'解析と変換',title:'Source Map / 元ファイルへ戻る',environment:'game',
  description:'通常とLifeBoatのビルド結果を、リンク前の各moduleへ対応付けます。マップのファイル一覧から元snapshotを選べます。',
  features:['build','buildLifeboat','sourceMap','sourceSnapshots','moduleComposition'],source:'local twice=require("lib")\nfunction onTick()output.setNumber(1,twice(input.getNumber(1)))end',
  steps:[{op:'buildLifeboat',project:{entry:'main',modules:{main:'require("lib")\nfunction onTick()output.setNumber(1,twice(3))end',lib:'function twice(value)return value*2 end'}},options:{sourceMap:true,minify:true},as:'lifeboat'},
   {op:'build',project:{entry:'main',modules:{main:source,lib:'return function(value)\n return value*2\nend'}},options:{environment,sourceMap:true,minify:false},as:'linked'},
   {op:'build',project:{entry:'main',modules:{main:source,lib:'return function(value)\n return value*2\nend'}},options:{environment,sourceMap:true,minify:true},as:'mapped'}]},
 {...base,id:'source-map-debug',group:'実行と描画',title:'Source Map / 停止・ログ・エラー',environment:'game',
  description:'元範囲から生成行へbreakpoint候補を設定し、実VMで停止・継続・意図したエラーを確認します。実行時に列は取得できず、元位置が複数なら候補として表示します。',
  features:['mappedLoad','mappedAction','breakpoints','stack','logs','runtimeErrors'],source:debugSource,
  steps:[{op:'build',project:{entry:'main',modules:{main:source}},options:{environment,sourceMap:true,minify:false},as:'mapped'},
   {op:'mappedLoad',artifact:mappedArtifact('mapped'),as:'loaded'},
   {op:'mappedAction',identity:ref('loaded.artifact'),action:'breakpoints',options:{source:0,start:debugSource.indexOf('output.setNumber'),end:debugSource.indexOf('output.setNumber')+16}},
   {op:'mappedAction',identity:ref('loaded.artifact'),action:'tick',as:'paused'},
   {op:'mappedAction',identity:ref('loaded.artifact'),action:'clearBreakpoints'},
   {op:'mappedAction',identity:ref('loaded.artifact'),action:'continue',as:'failed'}]},

 {...base,id:'source-loading',group:'解析と変換',title:'Source / requireと再初期化',environment:'extended',
  description:'ホストのソースを別チャンクとして読み込み、そのファイルで停止します。前置き・本体・後置きもresetで順に再実行します。',
  features:['requireLoader','sourceNames','includeOnce','loadHistory','resetReplay'],
  source:'require("utility")\nlocal mainLocal=3\nfunction onTick()output.setNumber(1,helper()+mainLocal)end',
  steps:[{op:'createVehicle',options:{environment},modules:{utility:{name:'@lib/utility.lua',source:'local private=4\nfunction helper()return shared+private end'}}},
   {op:'load',source:'shared=10',name:'@prefix.lua'},{op:'breakpoints',points:[{source:'@lib/utility.lua',line:2}]},
   {op:'load',source,name:'@main.lua'},{op:'stack'},{op:'breakpoints',points:[]},{op:'resume'},
   {op:'load',source:'shared=20',name:'@suffix.lua'},{op:'tick',as:'result'},{op:'reset'},{op:'tick',as:'afterReset'},{op:'hostCalls'}]},

 {...base,id:'vehicle',group:'実行と描画',title:'Vehicle / シグナルとモニター',environment:'game',
  description:'入力×Gainを計算します。プロパティ更新とresetの違い、複数draw、ログを確認できます。',
  features:['createVehicle','load','io','tick','draw','frame','setProperties','reset','logs'],
  source:'local gain=property.getNumber("Gain")\nlocal count=0\nfunction onTick()\n count=count+1\n output.setNumber(1,input.getNumber(1)*gain)\n output.setBool(1,input.getBool(1))\n debug.log("tick",count)\nend\nfunction onDraw()\n screen.setColor(8,20,30) screen.drawClear()\n screen.setColor(100,230,200) screen.drawRectF(2,2,screen.getWidth()-4,8)\n screen.setColor(240,250,255) screen.drawText(3,17,"LUA ENGINE")\nend',
  steps:[{op:'createVehicle',options:{environment,properties:{Gain:2}}},{op:'load',source},{op:'io',numbers:[3],booleans:[true]},{op:'tick',count:3,as:'initial'},{op:'draw',width:64,height:32},{op:'draw',width:96,height:32},{op:'frame'},{op:'properties',properties:{Gain:4}},{op:'tick',as:'cached'},{op:'reset'},{op:'io',numbers:[3]},{op:'tick',as:'resetResult'},{op:'draw',width:64,height:32},{op:'logs'}]},
 {...base,id:'compiler',group:'解析と変換',title:'Compiler / 複数モジュール',environment:'game',
  description:'同じプロジェクトを解析・非短縮リンク・最適化します。生成物はloadするまで実行されません。',
  features:['analyze','build','sourceMap','minify','passIds','passMetadata','scanProperties'],
  source:'local utility=require("utility")\nfunction onTick()\n output.setNumber(1,utility.twice(input.getNumber(1)))\nend',
  steps:[
   {op:'analyze',project:{entry:'main',modules:{main:source,utility:'return {twice=function(x)return x*2 end}'}},options:{environment}},
   {op:'build',project:{entry:'main',modules:{main:source,utility:'return {twice=function(x)return x*2 end}'}},options:{environment,minify:false},as:'linked'},
   {op:'minify',source:ref('linked.code'),options:{environment,numericMode:'exact',targetSize:8192},as:'compiled'},
   {op:'build',project:{entry:'main',modules:{main:source,utility:'return {twice=function(x)return x*2 end}'}},options:{environment,minify:true},as:'built'},
   {op:'scanProperties',source:'local gain=property.getNumber("Gain")'},
   {op:'build',project:{entry:'main',modules:{main:'function onTick()output.setNumber(1,sim.constant)end'},ambient:{sim:{members:{constant:{kind:'module',source:'return 14'}}}}},options:{minify:false},as:'ambient'},
   {op:'passIds'},{op:'passMetadata'},
   {op:'createVehicle',options:{environment}},{op:'load',source:ref('compiled.code')},{op:'io',numbers:[4]},{op:'tick',as:'result'},
  ]},
 {...base,id:'reflection',group:'解析と変換',title:'動的_ENV / 名前を保持する',environment:'game',
  description:'実行時にプロパティから名前を取得します。字句短縮は関数名と値の名前を変えません。',
  features:['_ENV','lexicalMinify','propertyText','dynamicFunction'],
  source:'caption="HELLO"\nfunction originalFunction() return 9 end\nfunction onTick()\n local key=property.getText("name")\n output.setNumber(1,_ENV[key]())\nend\nfunction onDraw()\n local key="caption"\n screen.setColor(100,230,200)\n screen.drawText(2,2,_ENV[key])\nend',
  steps:[{op:'minify',source,options:{environment,targetSize:8192},as:'compiled'},{op:'createVehicle',options:{environment,properties:{name:'originalFunction'}}},{op:'load',source:ref('compiled.code')},{op:'tick',as:'result'},{op:'draw',width:64,height:32}]},
 {...base,id:'environment',group:'環境と拡張',title:'Game / Extended の違い',environment:'game',
  description:'既定環境はdebug.logだけを提供します。拡張環境のpcall/printと、ホストデバッガは別の機能です。',
  features:['gameEnvironment','extendedEnvironment','debug.log','print','pcall','error'],
  source:'function onTick()\n for _,name in ipairs({"pcall","error","print"})do debug.log(name,type(_ENV[name]))end\n for key in pairs(debug)do debug.log("debug",key)end\nend',
  steps:[{op:'createVehicle',options:{environment}},{op:'load',source},{op:'tick'},{op:'logs'},{op:'createVehicle',id:'extended',options:{environment:'extended'}},{op:'load',id:'extended',source:'function onTick()local ok,v=pcall(function()return 7 end);print(ok,v);output.setNumber(1,v)end'},{op:'tick',id:'extended',as:'result'},{op:'enableLogs',id:'extended'},{op:'logs',id:'extended'},{op:'createVehicle',id:'manual',manualLogs:true},{op:'load',id:'manual',source:'debug.log("record")'},{op:'drainLogRecords',id:'manual'},{op:'load',id:'manual',source:'debug.log("bytes")'},{op:'drainLogs',id:'manual'},{op:'load',id:'manual',source:'debug.log("flush")'},{op:'flushLogs',id:'manual'},{op:'dispose',id:'manual'}]},
 {...base,id:'bindings',group:'環境と拡張',title:'ホスト関数 / 標準関数の置換',environment:'extended',
  description:'明示したテストホストがmath.absを99へ置換します。VM reset後も同じbindingsを使用します。',
  features:['hostBindings','hostOverrides','bindingPaths','resetBindings','ownedValues'],
  source:'function onTick()\n output.setNumber(1,math.abs(-3)+host.offset)\n output.setBool(1,pcall==nil)\n debug.log(host.echo(string.char(0,255),9223372036854775807))\nend',
  steps:[{op:'bindingPaths',bindings,as:'paths'},{op:'minify',source,options:{environment,hostBindings:ref('paths')},as:'compiled'},{op:'createVehicle',options:{environment,bindings}},{op:'load',source:ref('compiled.code')},{op:'tick',as:'result'},{op:'reset'},{op:'tick'},{op:'logs'},{op:'hostCalls'}]},
 {...base,id:'addon',group:'Addonと保存',title:'Addon / イベントとsavedata',environment:'game',
  description:'ホスト関数・メニュープロパティ・イベント・保存とreloadを試します。ゲーム世界や仮物理はありません。',
  features:['createAddon','start','dispatch','menuProperties','savedata','reload','destroy','server'],
  source:'local enabled=property.checkbox("Enabled",true)\nlocal rate=property.slider("Rate",1,10,1,2)\ng_savedata={count=0}\nfunction onCreate(new)\n g_savedata.created=new\n g_savedata.answer=server.answer()\n debug.log("created",new,enabled,rate)\nend\nfunction onTick(dt) g_savedata.count=g_savedata.count+dt end\nfunction onChatMessage(peer,name,message) g_savedata.message=message end\nfunction onDestroy() debug.log("destroyed") end',
  steps:[{op:'createAddon',options:{environment,properties:{Enabled:true,Rate:2}},server:{answer:{returns:[{$i64:'42'}]}}},{op:'load',source},{op:'menuProperties'},{op:'start'},{op:'tick',count:3},{op:'dispatch',callback:'onChatMessage',args:[1,'tester','hello']},{op:'savedata',as:'saved'},{op:'encodeSavedata',value:ref('saved'),as:'portable'},{op:'decodeSavedata',value:ref('portable'),as:'restored'},{op:'reload',value:ref('restored')},{op:'start'},{op:'savedata',as:'afterReload'},{op:'luaField',value:ref('afterReload'),key:'count'},{op:'destroy'},{op:'logs'},{op:'hostCalls'}]},
 {...base,id:'debugger',group:'実行と描画',title:'Debugger / 停止と検査',environment:'game',
  description:'ブレークポイントで停止し、stack・locals・upvalues・table・watchを確認します。Lua標準debugは不要です。',
  features:['breakpoints','stack','locals','upvalues','watch','expandTable','stepInto','stepOver','stepOut','resume'],
  source:'local state={count=0}\nfunction add(x)\n return x+1\nend\nfunction onTick()\n state.count=add(state.count)\n output.setNumber(1,state.count)\nend',
  steps:[{op:'createVehicle',options:{environment}},{op:'breakpoints',points:[{source:'=playground',line:6}]},{op:'load',source},{op:'tick'},{op:'stack'},{op:'locals'},{op:'upvalues'},{op:'watch',expression:'state',as:'table'},{op:'expandTable',handle:ref('table.handle')},{op:'breakpoints',points:[]},{op:'resume',mode:'into'},{op:'stack'},{op:'resume',mode:'over'},{op:'stack'},{op:'resume',mode:'out'},{op:'io',as:'result'},{op:'breakpoints',points:[{source:'=playground',line:6}]},{op:'tick'},{op:'breakpoints',points:[]},{op:'resume',mode:'continue'}]},
 {...base,id:'raster',group:'実行と描画',title:'Raster / Luaなしで描画',environment:'game',
  description:'DrawCommandを直接描画し、バイナリ命令列でも再実行します。Lua VMはロードしません。',
  features:['loadRaster','encodeCommands','DrawCommand','FrameLease','CanvasPresenter'],source:'-- この例はLuaを実行せず、操作列のDrawCommandを描画します。',
  steps:[{op:'createRaster',width:64,height:32},{op:'render',commands},{op:'encodeCommands',commands,as:'binary'},{op:'render',commands:ref('binary')},{op:'rasterFrame'},{op:'disposeRaster'}]},
 {...base,id:'services',group:'ホストサービス',title:'地図 / HTTPの明示配送',environment:'game',
  description:'地図は指定色のテスト画像、HTTPは手入力の返信です。ネットワークへの要求は送信しません。',
  features:['mapProvider','mapPalette','httpRequests','httpReply','cancelHttp'],
  source:'local reply=0\nfunction onTick() output.setNumber(1,reply) async.httpGet(8080,"/probe") end\nfunction httpReply(port,request,response) reply=tonumber(response);debug.log(port,request,response)end\nfunction onDraw()screen.setMapColorOcean(8,20,30);screen.drawMap(0,0,1);screen.setColor(240,250,255);screen.drawText(2,2,"HOST MAP")end',
  steps:[{op:'createVehicle',options:{environment},mapFixture:{rgba:[20,55,70,255]}},{op:'load',source},{op:'tick'},{op:'httpRequests',as:'requests'},{op:'httpReply',token:ref('requests.0.token'),reply:'7'},{op:'tick',as:'result'},{op:'httpRequests',as:'pending'},{op:'cancelHttp',token:ref('pending.0.token')},{op:'draw',width:64,height:32},{op:'logs'},{op:'hostCalls'}]},
 {...base,id:'values',group:'Addonと保存',title:'値 / i64・バイト列・保存形式',environment:'game',
  description:'文字列を勝手にUTF-8化せず、整数64bit・非有限数・負のゼロを保持したsavedata往復を確認します。',
  features:['LuaValue','luaTable','luaField','luaText','encodeSavedata','decodeSavedata','matrix'],
  source:'g_savedata={large=9223372036854775807,raw=string.char(0,255),negativeZero=-0.0,nan=0/0,transform=matrix.translation(1,2,3)}',
  steps:[{op:'createAddon',options:{environment}},{op:'load',source},{op:'start'},{op:'savedata',as:'saved'},{op:'encodeSavedata',value:ref('saved'),as:'encoded'},{op:'decodeSavedata',value:ref('encoded'),as:'decoded'},{op:'luaField',value:ref('decoded'),key:'large'},{op:'luaText',value:{$bytes:[83,68,75]}},{op:'luaField',value:ref('decoded'),key:'raw'}]},
 {...base,id:'errors',group:'環境と拡張',title:'制限 / 未対応を隠さない',environment:'game',
  description:'禁止関数・Addonコンパイル・命令制限・未提供ホストがどう失敗するかを確認します。',
  features:['limits','compilerDiagnostics','unsupportedAddonCompiler','missingHost'],
  source:'function onTick() pcall(function()return 7 end) end',
  steps:[{op:'analyze',project:{entry:'main',modules:{main:source}}},{op:'minify',source},{op:'minify',source:'return 1',options:{target:'addon'},expectError:'addon'},{op:'createVehicle',options:{instructionBudget:1000}},{op:'load',source:'while true do end',expectError:'instruction'},{op:'dispose'},{op:'createAddon'},{op:'load',source:'function onCreate()server.missing()end'},{op:'start',expectError:'nil'},{op:'dispose'}]},
 {...base,id:'catalog',group:'API一覧',title:'SDK / 公開カタログ',environment:'game',
  description:'環境、Vehicle/Addon API、イベント、Playground操作の一覧を取得します。WASMの初期化は不要です。',
  features:['apiCatalog','environmentCatalog','addonEvents'],source:'-- カタログの確認にはLuaの実行は不要です。',steps:[{op:'catalog'}]},
];
export function recipe(id:string):Recipe {const found=RECIPES.find(r=>r.id===id);if(!found)throw new Error(`確認例がありません: ${id}`);return structuredClone(found);}
