//! Exercise internal source attribution through actual audited optimization passes.
//! This is a development example, not the final build SDK Source Map v3 contract.
use std::error::Error;
use storm_lua_minify::{compile_code, CompileOptions};

fn main() -> Result<(), Box<dyn Error>> {
    let source = "local signal=input.getNumber(1) output.setNumber(1,signal+2 * 3)";
    let mut options = CompileOptions {
        origin_source: Some("controller.lua".into()),
        ..Default::default()
    };
    options.pass_toggles = storm_lua_minify::pass_ids::OPTIMIZATION_PASS_IDS
        .iter()
        .map(|&id| (id, false))
        .collect();
    for id in [
        "constant-folding",
        "scope-renaming",
        "redundant-parentheses-elimination",
    ] {
        options.pass_toggles.insert(id, true);
    }
    let plain = compile_code(
        source,
        &CompileOptions {
            origin_source: None,
            ..options.clone()
        },
    )?;
    let result = compile_code(source, &options)?;
    assert_eq!(result.code, plain.code);
    let origins = result.origins.ok_or("requested provenance is missing")?;
    origins.validate_for_code(&result.code)?;
    assert_eq!(origins.unknown_bytes(), 0);
    println!("Original: {source}\nGenerated: {}", result.code);
    for mapping in &origins.mappings {
        let Some(origin) = mapping
            .origin
            .and_then(|id| origins.origins.get(id as usize))
        else {
            println!("{}..{}: unknown", mapping.start, mapping.end);
            continue;
        };
        if let Some(span) = origin.primary {
            let source = &origins.sources[span.source as usize];
            println!(
                "{}..{} {:?} -> {} {}..{} {:?} ({:?}, {:?})",
                mapping.start,
                mapping.end,
                &result.code[mapping.start..mapping.end],
                source.name,
                span.start,
                span.end,
                &source.text[span.start..span.end],
                origin.kind,
                origin.precision
            );
        }
    }
    // Leave all optimizations enabled in the second run. Unannotated transforms
    // are explicitly unknown, not guessed from nearby surviving source locations.
    let full = compile_code(
        source,
        &CompileOptions {
            origin_source: Some("controller.lua".into()),
            ..Default::default()
        },
    )?;
    let full_origins = full.origins.ok_or("full-search provenance is missing")?;
    println!(
        "Full search: {}\nOrigin coverage: {} of {} generated bytes; unknown={}",
        full.code,
        full.code.len() - full_origins.unknown_bytes(),
        full.code.len(),
        full_origins.unknown_bytes()
    );
    if std::env::args().any(|arg| arg == "--audit") {
        // This single fixture detects lost provenance through a pass; a clean
        // count does not establish coverage of other transformations in that pass.
        for &id in storm_lua_minify::pass_ids::OPTIMIZATION_PASS_IDS {
            let mut trial = options.clone();
            for value in trial.pass_toggles.values_mut() {
                *value = false;
            }
            trial.pass_toggles.insert(id, true);
            let outcome = compile_code(source, &trial)?;
            let unknown = outcome
                .origins
                .as_ref()
                .ok_or("missing audit provenance")?
                .unknown_bytes();
            if unknown > 0 {
                println!(
                    "Audit fixture: {id}: unknown {unknown}/{}; {}",
                    outcome.code.len(),
                    outcome.code
                );
            }
        }
    }
    if std::env::args().any(|arg| arg == "--audit-cumulative") {
        // Registration order is diagnostic only, not optimizer execution order.
        let mut trial = options.clone();
        for value in trial.pass_toggles.values_mut() {
            *value = false;
        }
        for &id in storm_lua_minify::pass_ids::OPTIMIZATION_PASS_IDS {
            trial.pass_toggles.insert(id, true);
            let outcome = compile_code(source, &trial)?;
            let unknown = outcome
                .origins
                .as_ref()
                .ok_or("missing audit provenance")?
                .unknown_bytes();
            if unknown > 0 {
                println!(
                    "Cumulative fixture after {id}: unknown {unknown}/{}; {}",
                    outcome.code.len(),
                    outcome.code
                );
            }
        }
    }
    Ok(())
}
