//! Pack several records per integer without duplicating the replay call body.
//! Only complete groups are admitted: padding must never add screen calls.
//! The largest byte integer is < 92^8 < 2^53 and all decoding is integer-only.
use super::*;

pub(super) fn payloads(columns: &[Vec<i64>], count: usize) -> Vec<(Codec, String)> {
    let Some((
        Codec::PackedBytes {
            biases,
            radices,
            width: single_width,
        },
        _,
    )) = packed_payload_with_limit(columns, count, 8)
    else {
        return Vec::new();
    };
    let cardinality: i64 = radices.iter().product();
    if cardinality <= 1 {
        return Vec::new();
    }
    let mut out = Vec::new();
    let mut best_width = single_width;
    let mut best_rows = 1;
    for rows in 2..=8 {
        if !count.is_multiple_of(rows) {
            continue;
        }
        let Some(limit) = cardinality.checked_pow(rows as u32) else {
            break;
        };
        if limit > 92_i64.pow(8) {
            break;
        }
        let mut width = 1;
        let mut capacity = 92i64;
        while capacity < limit {
            width += 1;
            capacity *= 92;
        }
        // Keep only increasing-density candidates; the smaller group remains
        // available when its decoder is shorter after name allocation.
        if width * best_rows >= best_width * rows {
            continue;
        }
        best_width = width;
        best_rows = rows;
        let mut bytes = String::with_capacity(count / rows * width);
        for first in (0..count).step_by(rows) {
            let mut group = 0i64;
            for row in (first..first + rows).rev() {
                let value = columns
                    .iter()
                    .zip(&biases)
                    .zip(&radices)
                    .fold(0, |value, ((c, bias), radix)| value * radix + c[row] - bias);
                group = group * cardinality + value;
            }
            let mut divisor = capacity / 92;
            for _ in 0..width {
                bytes.push((group / divisor % 92 + 35) as u8 as char);
                divisor /= 92;
            }
        }
        out.push((
            Codec::GroupedBytes {
                biases: biases.clone(),
                radices: radices.clone(),
                width,
                rows,
            },
            bytes,
        ));
    }
    out
}

pub(super) fn emit_helper(
    ast: &mut Ast,
    shape: &Shape,
    symbol: SymbolId,
    serial: usize,
    trace: &mut Option<provenance::Trace>,
) -> NodeId {
    let Codec::GroupedBytes {
        biases,
        radices,
        width,
        rows,
    } = &shape.codec
    else {
        unreachable!("grouped codec required")
    };
    debug_assert!(!shape
        .args
        .iter()
        .flatten()
        .any(|a| matches!(a, Arg::Series(_))));
    // Reuse the canonical byte reader, column extraction, translations, and
    // call emitter. Only the generated replay loop is nested here; no user AST
    // is inspected or moved. The helper has exactly one generated byte loop.
    let mut inner = shape.clone();
    inner.codec = Codec::PackedBytes {
        biases: biases.clone(),
        radices: radices.clone(),
        width: *width,
    };
    let declaration = super::encoding::emit_helper_recording(ast, &inner, symbol, serial, trace);
    let index = ast.strings.intern(&format!("__draw_i_{serial}"));
    let packed = ast.strings.intern(&format!("__draw_p_{serial}"));
    let group = ast.strings.intern(&format!("__draw_group_{serial}"));
    let row = ast.strings.intern(&format!("__draw_row_{serial}"));
    let mut byte_loop = None;
    storm_lua_syntax::ast_utils::walk(ast, declaration, &mut |id| {
        if matches!(ast.node(id), Node::Fornum(s, ..) if *s == index) {
            byte_loop = Some(id)
        }
    });
    #[expect(
        clippy::expect_used,
        reason = "The decoder declaration was just generated with this byte-loop index binding"
    )]
    let Node::Fornum(_, _, _, _, block) = ast.node(byte_loop.expect("generated byte loop")) else {
        unreachable!()
    };
    let block = *block;
    let Node::Block(statements) = ast.node(block) else {
        unreachable!()
    };
    // First statement reads bytes, second reconstructs the bounded integer.
    let mut statements = statements.clone();
    let Node::Local(_, values) = ast.node(statements[1]) else {
        unreachable!()
    };
    ast.nodes[statements[1] as usize] = Node::Local(vec![group], values.clone());
    let cardinality: i64 = radices.iter().product();
    let g = name(ast, group);
    let n = num(ast, cardinality);
    let value = ast.push(Node::Bin("%".into(), g, n));
    let mut replay = vec![ast.push(Node::Local(vec![packed], vec![value]))];
    replay.extend(statements.drain(2..));
    let lhs = name(ast, group);
    let g = name(ast, group);
    let n = num(ast, cardinality);
    let rest = ast.push(Node::Bin("//".into(), g, n));
    replay.push(ast.push(Node::Assign(vec![lhs], vec![rest])));
    let body = ast.push(Node::Block(replay));
    let first = num(ast, 1);
    let last = num(ast, *rows as i64);
    statements.push(ast.push(Node::Fornum(row, first, last, None, body)));
    ast.nodes[block as usize] = Node::Block(statements);
    declaration
}
