//! Prefix-free records with adjacent short/long widths (e.g. two/three bytes).
//! The first digit chooses the width; no terminator, ambiguity, or padding.
use super::*;

pub(super) fn emit_helper(
    ast: &mut Ast,
    shape: &Shape,
    symbol: SymbolId,
    serial: usize,
    trace: &mut Option<provenance::Trace>,
) -> NodeId {
    let Codec::PrefixBytes {
        biases,
        radices,
        width,
        prefixes,
    } = &shape.codec
    else {
        unreachable!()
    };
    debug_assert!(!shape
        .args
        .iter()
        .flatten()
        .any(|a| matches!(a, Arg::Series(_))));
    let mut fixed = shape.clone();
    fixed.codec = Codec::PackedBytes {
        biases: biases.clone(),
        radices: radices.clone(),
        width: *width,
    };
    let declaration = super::encoding::emit_helper_recording(ast, &fixed, symbol, serial, trace);
    let index = ast.strings.intern(&format!("__draw_i_{serial}"));
    let data = ast.strings.intern(&format!("__draw_d_{serial}"));
    let packed = ast.strings.intern(&format!("__draw_p_{serial}"));
    let first_byte = ast.strings.intern(&format!("__draw_b_{serial}_0"));
    let mut generated_loop = None;
    storm_lua_syntax::ast_utils::walk(ast, declaration, &mut |n| {
        if matches!(ast.node(n),Node::Fornum(s,..) if *s==index) {
            generated_loop = Some(n)
        }
    });
    #[expect(
        clippy::expect_used,
        reason = "The preceding decoder generator creates a numeric byte loop with this exact index binding"
    )]
    let loop_id = generated_loop.expect("generated byte loop");
    let Node::Fornum(_, _, _, _, body) = ast.node(loop_id) else {
        unreachable!()
    };
    let body = *body;
    let Node::Block(stmts) = ast.node(body) else {
        unreachable!()
    };
    let mut stmts = stmts.clone();
    let cutoff = *prefixes as i64 * 92i64.pow(*width as u32 - 1);
    let i = name(ast, index);
    let current = name(ast, index);
    let next = offset(ast, current, *width as i64);
    let advance = ast.push(Node::Assign(vec![i], vec![next]));
    let byte = name(ast, first_byte);
    let threshold = num(ast, *prefixes as i64 + 35);
    let condition = ast.push(Node::Bin(">=".into(), byte, threshold));
    let p = name(ast, packed);
    let remainder = offset(ast, p, -cutoff);
    let radix = num(ast, 92);
    let rest = ast.push(Node::Bin("*".into(), remainder, radix));
    let d = name(ast, data);
    let i = name(ast, index);
    let last = ast.push(Node::Call(d, vec![i], Some("byte".into())));
    let joined = ast.push(Node::Bin("+".into(), rest, last));
    let decoded = offset(ast, joined, cutoff - 35);
    let lhs = name(ast, packed);
    let assign = ast.push(Node::Assign(vec![lhs], vec![decoded]));
    let i = name(ast, index);
    let current = name(ast, index);
    let next = offset(ast, current, 1);
    let skip = ast.push(Node::Assign(vec![i], vec![next]));
    let long = ast.push(Node::Block(vec![assign, skip]));
    let branch = ast.push(Node::If(
        vec![storm_lua_syntax::ast::IfArm {
            cond: condition,
            body: long,
        }],
        None,
    ));
    stmts.splice(2..2, [advance, branch]);
    ast.nodes[body as usize] = Node::Block(stmts);
    let i = name(ast, index);
    let d = name(ast, data);
    let length = ast.push(Node::Un("#".into(), d));
    let condition = ast.push(Node::Bin("<=".into(), i, length));
    let while_ = ast.push(Node::While(condition, body));
    let one = num(ast, 1);
    let initial = ast.push(Node::Local(vec![index], vec![one]));
    let block = ast.push(Node::Block(vec![initial, while_]));
    ast.nodes[loop_id as usize] = Node::Do(block);
    declaration
}
